version: '{build}-{branch}'
image: Visual Studio 2015
environment:
  root_dir: '%APPVEYOR_BUILD_FOLDER%\'
  source_dir: '%root_dir%src\'
  project_name: 'Source.JetBrains.Annotations'
  nuspec_file: '%source_dir%%project_name%.nuspec'
  version_file: '%source_dir%gitversion.out'
install:
- cmd: choco install %root_dir%packages.config -y
before_build:
- cmd: gitversion /showvariable NuGetVersionV2 > %version_file%
- cmd: SET /P version=<%version_file%
build_script: nuget pack "%nuspec_file%" -properties "Version=%version%;id=%project_name%"
after_build:
- cmd: appveyor PushArtifact "%root_dir%\%project_name%.%version%.nupkg"
deploy:
- provider: NuGet
  name: MyGet
  server: https://www.myget.org/F/dittodhole/api/v2/package
  api_key:
    secure: c9r6oyxFOqnfj0xezZcLIoopgoBUb5ib9nrTYMkXDTqzvMrrXmprbHgyldag6NZ4
  on:
    branch: develop
- provider: NuGet
  name: NuGet
  api_key:
    secure: U6199dIr+h5NLeO9aWtxR2ihfMjDX3rrhqjdN3ByzlLzU9t3T00+MtjNQPkfrToY
  on:
    branch: master
- provider: NuGet
  name: NuGet (pre release)
  api_key:
    secure: U6199dIr+h5NLeO9aWtxR2ihfMjDX3rrhqjdN3ByzlLzU9t3T00+MtjNQPkfrToY
  on:
    branch: /release\/.*/